import { describe, expect, it } from 'vitest';
import {
  buildPullRequestFindingCommentBody,
  parseAdoRemoteUrl,
  parseGitHubRemoteUrl,
} from '../code-review-pr.service.js';

describe('parseGitHubRemoteUrl', () => {
  it('parses HTTPS GitHub remotes', () => {
    expect(parseGitHubRemoteUrl('https://github.com/acme/devhub.git')).toEqual({
      provider: 'github',
      host: 'github.com',
      owner: 'acme',
      repo: 'devhub',
    });
  });

  it('parses SSH GitHub remotes', () => {
    expect(parseGitHubRemoteUrl('git@github.com:acme/devhub.git')).toEqual({
      provider: 'github',
      host: 'github.com',
      owner: 'acme',
      repo: 'devhub',
    });
  });
});

describe('parseAdoRemoteUrl', () => {
  it('parses dev.azure.com remotes', () => {
    expect(
      parseAdoRemoteUrl('https://dev.azure.com/example-org/Platform/_git/Developer%20Hub'),
    ).toEqual({
      provider: 'ado',
      baseUrl: 'https://dev.azure.com/example-org',
      project: 'Platform',
      repo: 'Developer Hub',
    });
  });

  it('parses visualstudio.com remotes', () => {
    expect(
      parseAdoRemoteUrl('https://example-org.visualstudio.com/Platform/_git/DeveloperHub'),
    ).toEqual({
      provider: 'ado',
      baseUrl: 'https://example-org.visualstudio.com',
      project: 'Platform',
      repo: 'DeveloperHub',
    });
  });
});

describe('buildPullRequestFindingCommentBody', () => {
  it('includes severity, category, location, description, and suggestion', () => {
    const body = buildPullRequestFindingCommentBody({
      id: 'finding-1',
      reviewId: 'review-1',
      severity: 'major',
      category: 'Correctness',
      filePath: 'src/main/service.ts',
      lineStart: 42,
      lineEnd: 45,
      description: 'The fallback path swallows the original error and makes debugging harder.',
      suggestion: 'Preserve the error context or wrap it with the original cause attached.',
      dismissed: false,
    });

    expect(body).toContain('Anvil code review finding');
    expect(body).toContain('Severity: major');
    expect(body).toContain('Category: Correctness');
    expect(body).toContain('Location: src/main/service.ts:42-45');
    expect(body).toContain('Issue:');
    expect(body).toContain('Suggestion:');
    expect(body).toContain('_Generated by Anvil Code Review._');
  });

  it('omits optional sections when the finding has no location or suggestion', () => {
    const body = buildPullRequestFindingCommentBody({
      id: 'finding-2',
      reviewId: 'review-1',
      severity: 'suggestion',
      category: 'Maintainability',
      description: 'Consider simplifying this branching structure.',
      dismissed: false,
    });

    expect(body).not.toContain('Location:');
    expect(body).not.toContain('Suggestion:');
  });
});
