import type { Persona } from '../../shared/types.js';

/**
 * Compiled-in personas. Data-only leaf module so both the persona service
 * (prompt rendering, repo context) and sync codecs (reference validation)
 * can resolve builtin ids without pulling the service dependency chain.
 */
export const PERSONAS: Persona[] = [
  {
    id: 'coder',
    name: 'Coder',
    icon: 'Code',
    colour: '#22c55e',
    description: 'General purpose coding agent. Writes, edits, and runs code.',
    systemPromptTemplate: 'personas/coder.md',
    capabilities: { canWriteFiles: true, canRunCommands: true, canReadFiles: true },
  },
  {
    id: 'mentor',
    name: 'Dev Mentor',
    icon: 'GraduationCap',
    colour: '#0f766e',
    description:
      'Guides junior developers through multiple approaches, optimisation tradeoffs, and debugging steps.',
    systemPromptTemplate: 'personas/mentor.md',
    capabilities: { canWriteFiles: true, canRunCommands: true, canReadFiles: true },
  },
  {
    id: 'architect',
    name: 'Architect',
    icon: 'Building2',
    colour: '#3b82f6',
    description: 'Analyses structure and design. Does not modify code.',
    systemPromptTemplate: 'personas/architect.md',
    capabilities: { canWriteFiles: false, canRunCommands: false, canReadFiles: true },
  },
  {
    id: 'security',
    name: 'Security',
    icon: 'Shield',
    colour: '#ef4444',
    description: 'Scans for vulnerabilities. Can run analysis tools but does not edit code.',
    systemPromptTemplate: 'personas/security.md',
    capabilities: { canWriteFiles: false, canRunCommands: true, canReadFiles: true },
  },
  {
    id: 'reviewer',
    name: 'Code Reviewer',
    icon: 'Eye',
    colour: '#eab308',
    description: 'Reviews code against conventions and best practices.',
    systemPromptTemplate: 'personas/reviewer.md',
    capabilities: { canWriteFiles: false, canRunCommands: false, canReadFiles: true },
  },
  {
    id: 'docs',
    name: 'Documentation',
    icon: 'BookOpen',
    colour: '#8b5cf6',
    description: 'Writes and updates documentation files only.',
    systemPromptTemplate: 'personas/docs.md',
    capabilities: { canWriteFiles: true, canRunCommands: false, canReadFiles: true },
  },
  {
    id: 'ba',
    name: 'Business Analyst',
    icon: 'ClipboardList',
    colour: '#7c3aed',
    description:
      'Analyse requirements, assess feasibility, flag compliance concerns, create spikes.',
    systemPromptTemplate: 'personas/ba.md',
    capabilities: { canWriteFiles: true, canRunCommands: true, canReadFiles: true },
  },
  {
    id: 'workshop-planner',
    name: 'Workshop Planner',
    icon: 'Presentation',
    colour: '#f97316',
    description:
      'Plans discovery sessions, stakeholder workshops, agendas, decision framing, and facilitation outputs.',
    systemPromptTemplate: 'personas/workshop-planner.md',
    capabilities: { canWriteFiles: true, canRunCommands: false, canReadFiles: true },
  },
  {
    id: 'service-desk',
    name: 'Service Desk Analyst',
    icon: 'Headphones',
    colour: '#38bdf8',
    description: 'Structures first-line intake, troubleshooting, classification, and handover.',
    systemPromptTemplate: 'personas/service-desk.md',
    capabilities: { canWriteFiles: false, canRunCommands: false, canReadFiles: true },
  },
  {
    id: 'technical-support',
    name: 'Technical Support Analyst',
    icon: 'Wrench',
    colour: '#2dd4bf',
    description: 'Investigates technical evidence and prepares clear second-line escalations.',
    systemPromptTemplate: 'personas/technical-support.md',
    capabilities: { canWriteFiles: false, canRunCommands: true, canReadFiles: true },
  },
  {
    id: 'incident-manager',
    name: 'Incident Manager',
    icon: 'Radio',
    colour: '#fb7185',
    description: 'Coordinates restoration, decisions, timelines, ownership, and communications.',
    systemPromptTemplate: 'personas/incident-manager.md',
    capabilities: { canWriteFiles: false, canRunCommands: false, canReadFiles: true },
  },
  {
    id: 'problem-manager',
    name: 'Problem Manager',
    icon: 'SearchCheck',
    colour: '#c084fc',
    description: 'Separates symptoms from causes and develops evidence-backed corrective actions.',
    systemPromptTemplate: 'personas/problem-manager.md',
    capabilities: { canWriteFiles: false, canRunCommands: false, canReadFiles: true },
  },
  {
    id: 'change-manager',
    name: 'Change Manager',
    icon: 'GitPullRequest',
    colour: '#fbbf24',
    description: 'Assesses change risk, dependencies, validation, approvals, and backout plans.',
    systemPromptTemplate: 'personas/change-manager.md',
    capabilities: { canWriteFiles: false, canRunCommands: false, canReadFiles: true },
  },
  {
    id: 'service-manager',
    name: 'Service Manager',
    icon: 'Gauge',
    colour: '#a3e635',
    description: 'Prepares service reviews, measures outcomes, and shapes continual improvement.',
    systemPromptTemplate: 'personas/service-manager.md',
    capabilities: { canWriteFiles: false, canRunCommands: false, canReadFiles: true },
  },
  {
    id: 'design',
    name: 'Design Companion',
    icon: 'Palette',
    colour: '#ec4899',
    description: 'Design with Figma or implement designs into code.',
    systemPromptTemplate: 'personas/design.md',
    capabilities: { canWriteFiles: false, canRunCommands: false, canReadFiles: true },
  },
  {
    id: 'db-expert',
    name: 'DB Expert',
    icon: 'Database',
    colour: '#14b8a6',
    description: 'Explains schemas, stored procedures, and SQL Server database design.',
    systemPromptTemplate: 'personas/db-expert.md',
    capabilities: { canWriteFiles: false, canRunCommands: false, canReadFiles: true },
  },
];
